In [11]:
# CÉLULA 1: Configuração do ambiente e definição de caminhos.
# Aqui importamos as bibliotecas necessárias e definimos onde o arquivo está localizado.
# O uso de '..' serve para subir um nível de pasta (de /notebooks para a raiz do projeto).
import pandas as pd
import os
#NOTE: Mude o arquivo alvo aqui.
ARQUIVO_ALVO = "3-tabelas_dezembro-de-2023_Tabela_3.csv" 

CAMINHO_DADOS = os.path.join("..", "data", "processed", "caged", "2023", ARQUIVO_ALVO)

print(f"✅ Caminho configurado.")
print(f"🔍 Olhando em: {os.path.abspath(CAMINHO_DADOS)}")

✅ Caminho configurado.
🔍 Olhando em: /home/lk2424/GitRepo/lucaspaiva-lp/rs-impact/data/processed/caged/2023/3-tabelas_dezembro-de-2023_Tabela_3.csv

In [12]:
# CÉLULA 2: Carregamento dos dados para a memória RAM.
# Verifica se o arquivo existe antes de tentar ler para evitar erros de execução.
# O encoding 'utf-8-sig' garante a leitura correta de acentos em arquivos CSV vindos do Excel.
if os.path.exists(CAMINHO_DADOS):
    df = pd.read_csv(CAMINHO_DADOS, encoding='utf-8-sig')
    print(f"📊 Sucesso! O arquivo tem {df.shape[0]} linhas e {df.shape[1]} colunas.")
else:
    print(f"❌ Erro: Arquivo não encontrado em {os.path.abspath(CAMINHO_DADOS)}")

📊 Sucesso! O arquivo tem 5575 linhas e 11 colunas.

In [13]:
# CÉLULA 3: Visualização inicial da estrutura dos dados.
# Mostra as 10 primeiras linhas para entendermos o formato das informações e como elas estão distribuídas.
df.head(10)

,UF,Código do Município,Município,Dezembro/2023 - sem ajuste Admissões,Dezembro/2023 - sem ajuste Desligamentos,Dezembro/2023 - sem ajuste Saldos,Dezembro/2023 - sem ajuste Variação Relativa (%),Acumulado do Ano (2023) Admissões,Acumulado do Ano (2023) Desligamentos,Acumulado do Ano (2023) Saldos,Acumulado do Ano (2023) Variação Relativa (%)
0,RO,110001.0,Ro-Alta Floresta D Oeste,56.0,97.0,-41.0,-2.0438683948155534,1188.0,1156.0,32.0,1.6376663254861823
1,RO,110002.0,Ro-Ariquemes,583.0,675.0,-92.0,-0.5067753663104549,11642.0,11035.0,607.0,3.443971631205674
2,RO,110003.0,Ro-Cabixi,10.0,6.0,4.0,0.9009009009009009,193.0,190.0,3.0,0.6651884700665188
3,RO,110004.0,Ro-Cacoal,753.0,774.0,-21.0,-0.12190166598943519,11617.0,11153.0,464.0,2.7647023774057082
4,RO,110005.0,Ro-Cerejeiras,90.0,94.0,-4.0,-0.17086715079026057,1455.0,1328.0,127.0,5.746606334841629
5,RO,110006.0,Ro-Colorado do Oeste,47.0,54.0,-7.0,-0.358974358974359,928.0,970.0,-42.0,-2.1549512570549
6,RO,110007.0,Ro-Corumbiara,46.0,62.0,-16.0,-1.1816838995568686,1038.0,828.0,210.0,18.71657754010695
7,RO,110008.0,Ro-Costa Marques,12.0,19.0,-7.0,-1.2681159420289856,264.0,268.0,-4.0,-0.7259528130671506
8,RO,110009.0,Ro-Espigao D Oeste,164.0,228.0,-64.0,-1.3608335105251965,2957.0,2924.0,33.0,0.7205240174672489
9,RO,110010.0,Ro-Guajara-Mirim,101.0,219.0,-118.0,-3.320202588632527,1888.0,1565.0,323.0,10.231232182451695

In [14]:
# CÉLULA 4: Listagem técnica das colunas.
# Essencial para identificar os nomes exatos das colunas (UF, Município, Saldos, etc.)
# Serve como guia para configurar os filtros nas próximas etapas de análise.
print("🔍 Colunas encontradas no arquivo:")
for i, col in enumerate(df.columns):
    print(f"Coluna {i}: '{col}'")

🔍 Colunas encontradas no arquivo:
Coluna 0: 'UF'
Coluna 1: 'Código do Município'
Coluna 2: 'Município'
Coluna 3: 'Dezembro/2023 - sem ajuste Admissões'
Coluna 4: 'Dezembro/2023 - sem ajuste Desligamentos'
Coluna 5: 'Dezembro/2023 - sem ajuste Saldos'
Coluna 6: 'Dezembro/2023 - sem ajuste Variação Relativa (%)'
Coluna 7: 'Acumulado do Ano (2023) Admissões'
Coluna 8: 'Acumulado do Ano (2023) Desligamentos'
Coluna 9: 'Acumulado do Ano (2023) Saldos'
Coluna 10: 'Acumulado do Ano (2023) Variação Relativa (%)'

In [15]:
# CÉLULA 5: Extração e filtragem dos dados de interesse.
# Filtra o DataFrame original para isolar apenas os registros do Rio Grande do Sul (RS).
# Essa célula transforma o dado bruto em dado útil para o projeto rs-impact.

#NOTE: Troque para a coluna desejada.
coluna_desejada = 'UF' 

if coluna_desejada in df.columns:
    df_rs = df[df[coluna_desejada].str.contains('RS', na=False)]
    print(f"📍 Registros do RS: {len(df_rs)}")
    display(df_rs.head())
else:
    print(f"⚠️ A coluna '{coluna_desejada}' não foi encontrada neste arquivo.")

📍 Registros do RS: 497

,UF,Código do Município,Município,Dezembro/2023 - sem ajuste Admissões,Dezembro/2023 - sem ajuste Desligamentos,Dezembro/2023 - sem ajuste Saldos,Dezembro/2023 - sem ajuste Variação Relativa (%),Acumulado do Ano (2023) Admissões,Acumulado do Ano (2023) Desligamentos,Acumulado do Ano (2023) Saldos,Acumulado do Ano (2023) Variação Relativa (%)
4606,RS,430003.0,Rs-Acegua,27.0,26.0,1.0,0.10869565217391304,402.0,358.0,44.0,4.8997772828507795
4607,RS,430005.0,Rs-Agua Santa,13.0,12.0,1.0,0.17271157167530224,251.0,193.0,58.0,11.02661596958175
4608,RS,430010.0,Rs-Agudo,37.0,65.0,-28.0,-1.1508425811755036,1003.0,925.0,78.0,3.340471092077088
4609,RS,430020.0,Rs-Ajuricaba,28.0,43.0,-15.0,-1.4299332697807436,583.0,531.0,52.0,5.333333333333334
4610,RS,430030.0,Rs-Alecrim,11.0,8.0,3.0,0.7692307692307693,155.0,159.0,-4.0,-1.0050251256281406