In [6]:
# CÉLULA 1: Configuração do ambiente e definição de caminhos.
import pandas as pd
from pathlib import Path

#NOTE: Defina o arquivo e o ano processado.
ARQUIVO_ALVO = "12-tabelas-dezembro-de-2024_tabela_3.parquet"
ANO = "2024"

RAIZ = Path("..").resolve().parents[0]
CAMINHO_DADOS = RAIZ / "rs-impact" / "data" / "processed" / "caged" / ANO / ARQUIVO_ALVO

print(f"✅ Caminho configurado.")
print(f"🔍 Alvo: {CAMINHO_DADOS}")

✅ Caminho configurado.
🔍 Alvo: /home/lk1048/repositories/academic/estacio/ads-3-periodo/big-data/rs-impact/data/processed/caged/2024/12-tabelas-dezembro-de-2024_tabela_3.parquet

In [7]:
# CÉLULA 2: Carregamento dos dados para a memória RAM.
if CAMINHO_DADOS.exists():
    df = pd.read_parquet(CAMINHO_DADOS)
    print(f"📊 Sucesso! O arquivo tem {df.shape[0]} linhas e {df.shape[1]} colunas.")
else:
    print(f"❌ Erro: Arquivo não encontrado em {CAMINHO_DADOS}")

📊 Sucesso! O arquivo tem 497 linhas e 12 colunas.

In [8]:
# CÉLULA 3: Visualização inicial da estrutura dos dados.
df.head(10)

,coluna_0,uf,código_do_município,município,dezembro2024_sem_ajuste_admissões,dezembro2024_sem_ajuste_desligamentos,dezembro2024_sem_ajuste_saldos,dezembro2024_sem_ajuste_variação_relativa,acumulado_do_ano_2024_com_ajustes_admissões,acumulado_do_ano_2024_com_ajustes_desligamentos,acumulado_do_ano_2024_com_ajustes_saldos,acumulado_do_ano_2024_com_ajustes_variação_relativa
0,NaN,RS,430003.0,Rs-Acegua,53.0,39.0,14.0,1.307190,509.0,471.0,38.0,3.629417
1,NaN,RS,430005.0,Rs-Agua Santa,14.0,24.0,-10.0,-1.814882,239.0,274.0,-35.0,-6.076389
2,NaN,RS,430010.0,Rs-Agudo,76.0,91.0,-15.0,-0.619067,1029.0,1039.0,-10.0,-0.413565
3,NaN,RS,430020.0,Rs-Ajuricaba,19.0,38.0,-19.0,-1.595298,580.0,514.0,66.0,5.967450
4,NaN,RS,430030.0,Rs-Alecrim,12.0,14.0,-2.0,-0.490196,148.0,135.0,13.0,3.307888
5,NaN,RS,430040.0,Rs-Alegrete,393.0,384.0,9.0,0.069391,5092.0,4841.0,251.0,1.972030
6,NaN,RS,430045.0,Rs-Alegria,6.0,30.0,-24.0,-9.302326,136.0,135.0,1.0,0.429185
7,NaN,RS,430047.0,Rs-Almirante Tamandare do Sul,47.0,21.0,26.0,4.459691,450.0,370.0,80.0,15.122873
8,NaN,RS,430050.0,Rs-Alpestre,10.0,24.0,-14.0,-2.247191,280.0,269.0,11.0,1.839465
9,NaN,RS,430055.0,Rs-Alto Alegre,3.0,3.0,0.0,0.000000,35.0,39.0,-4.0,-2.898551

In [9]:
# CÉLULA 4: Listagem técnica das colunas.
print("🔍 Colunas encontradas (Normalizadas):")
for i, col in enumerate(df.columns):
    print(f"Coluna {i}: '{col}'")

🔍 Colunas encontradas (Normalizadas):
Coluna 0: 'coluna_0'
Coluna 1: 'uf'
Coluna 2: 'código_do_município'
Coluna 3: 'município'
Coluna 4: 'dezembro2024_sem_ajuste_admissões'
Coluna 5: 'dezembro2024_sem_ajuste_desligamentos'
Coluna 6: 'dezembro2024_sem_ajuste_saldos'
Coluna 7: 'dezembro2024_sem_ajuste_variação_relativa'
Coluna 8: 'acumulado_do_ano_2024_com_ajustes_admissões'
Coluna 9: 'acumulado_do_ano_2024_com_ajustes_desligamentos'
Coluna 10: 'acumulado_do_ano_2024_com_ajustes_saldos'
Coluna 11: 'acumulado_do_ano_2024_com_ajustes_variação_relativa'

In [10]:
# CÉLULA 5: Diagnóstico de Escopo Econômico (Nacional vs Estadual)

print("📋 Primeiras linhas para entender o conteúdo real:")
display(df.head(10))

# Vamos procurar se existe alguma coluna que faça referência a Estados (UF) ou Regiões
colunas_uf = [col for col in df.columns if 'uf' in col.lower() or 'estado' in col.lower() or 'região' in col.lower()]

if colunas_uf:
    print(f"📍 Colunas de localização encontradas: {colunas_uf}")
    for col in colunas_uf:
        print(f"\nValores únicos na coluna '{col}':")
        print(df[col].unique())
else:
    print("\n⚠️ Nenhuma coluna explícita de 'UF' ou 'Estado' foi encontrada.")
    print("Isso indica que esta tabela específica pode ser um consolidado Nacional ou Setorial puro.")

📋 Primeiras linhas para entender o conteúdo real:

,coluna_0,uf,código_do_município,município,dezembro2024_sem_ajuste_admissões,dezembro2024_sem_ajuste_desligamentos,dezembro2024_sem_ajuste_saldos,dezembro2024_sem_ajuste_variação_relativa,acumulado_do_ano_2024_com_ajustes_admissões,acumulado_do_ano_2024_com_ajustes_desligamentos,acumulado_do_ano_2024_com_ajustes_saldos,acumulado_do_ano_2024_com_ajustes_variação_relativa
0,NaN,RS,430003.0,Rs-Acegua,53.0,39.0,14.0,1.307190,509.0,471.0,38.0,3.629417
1,NaN,RS,430005.0,Rs-Agua Santa,14.0,24.0,-10.0,-1.814882,239.0,274.0,-35.0,-6.076389
2,NaN,RS,430010.0,Rs-Agudo,76.0,91.0,-15.0,-0.619067,1029.0,1039.0,-10.0,-0.413565
3,NaN,RS,430020.0,Rs-Ajuricaba,19.0,38.0,-19.0,-1.595298,580.0,514.0,66.0,5.967450
4,NaN,RS,430030.0,Rs-Alecrim,12.0,14.0,-2.0,-0.490196,148.0,135.0,13.0,3.307888
5,NaN,RS,430040.0,Rs-Alegrete,393.0,384.0,9.0,0.069391,5092.0,4841.0,251.0,1.972030
6,NaN,RS,430045.0,Rs-Alegria,6.0,30.0,-24.0,-9.302326,136.0,135.0,1.0,0.429185
7,NaN,RS,430047.0,Rs-Almirante Tamandare do Sul,47.0,21.0,26.0,4.459691,450.0,370.0,80.0,15.122873
8,NaN,RS,430050.0,Rs-Alpestre,10.0,24.0,-14.0,-2.247191,280.0,269.0,11.0,1.839465
9,NaN,RS,430055.0,Rs-Alto Alegre,3.0,3.0,0.0,0.000000,35.0,39.0,-4.0,-2.898551

📍 Colunas de localização encontradas: ['uf']

Valores únicos na coluna 'uf':
<ArrowStringArray>
['RS']
Length: 1, dtype: str

In [12]:
# CÉLULA 6: Verificação de linhas de somatório (Subtotais) - CORRIGIDA
linhas_suspeitas = df[df['município'].str.contains('total|ignorado|subtotal', case=False, na=False)]

if not linhas_suspeitas.empty:
    print("⚠️ Atenção! Foram encontradas linhas de agregação na tabela:")
    display(linhas_suspeitas[['município', 'dezembro2024_sem_ajuste_saldos']])
else:
    print("✅ Limpo! A tabela só contém municípios puros.")

✅ Limpo! A tabela só contém municípios puros.

In [13]:
# CÉLULA 7: Consolidação estatística para o estado do Rio Grande do Sul
saldo_mes_rs = df['dezembro2024_sem_ajuste_saldos'].sum()
admissoes_mes_rs = df['dezembro2024_sem_ajuste_admissões'].sum()
desligamentos_mes_rs = df['dezembro2024_sem_ajuste_desligamentos'].sum()

acumulado_saldo_ano_rs = df['acumulado_do_ano_2024_com_ajustes_saldos'].sum()

print(f"📊 --- Consolidação RS ({ARQUIVO_ALVO}) ---")
print(f"💼 Admissões no Mês: {admissoes_mes_rs:,.0f}".replace(",", "."))
print(f"📉 Desligamentos no Mês: {desligamentos_mes_rs:,.0f}".replace(",", "."))
print(f"🟩 Saldo Líquido do Mês (Dez/2024): {saldo_mes_rs:,.0f}".replace(",", "."))
print(f"🏆 Saldo Acumulado do Ano (2024): {acumulado_saldo_ano_rs:,.0f}".replace(",", "."))

📊 --- Consolidação RS (12-tabelas-dezembro-de-2024_tabela_3.parquet) ---
💼 Admissões no Mês: 95.156
📉 Desligamentos no Mês: 123.540
🟩 Saldo Líquido do Mês (Dez/2024): -28.384
🏆 Saldo Acumulado do Ano (2024): 63.551

In [14]:
# CÉLULA 8: Varredura de arquivos e construção da série temporal do CAGED
import re

pasta_2024 = CAMINHO_DADOS.parent
arquivos_parquet = sorted(list(pasta_2024.glob("*.parquet")))

dados_serie_temporal = []

print(f"🔄 Iniciando processamento de {len(arquivos_parquet)} arquivos em {pasta_2024.name}...\n")

for caminho_arq in arquivos_parquet:
    nome_fich = caminho_arq.name
    
    # Extrai o número do mês do nome do arquivo (ex: "12-tabelas..." -> "12")
    match_mes = re.search(r'^(\d+)', nome_fich)
    if not match_mes:
        continue
    mes = match_mes.group(1).zfill(2)
    ano_mes = f"{ANO}-{mes}"
    
    try:
        df_mes = pd.read_parquet(caminho_arq)
        
        # Identifica dinamicamente a coluna de saldo daquele mês específico
        coluna_saldo = [col for col in df_mes.columns if 'saldos' in col.lower() and 'acumulado' not in col.lower()]
        
        if coluna_saldo:
            col_alvo = coluna_saldo[0]
            # Filtra garantindo apenas municípios puros (evitando possíveis subtotais)
            df_limpo = df_mes[~df_mes['município'].str.contains('total|ignorado|subtotal', case=False, na=False)]
            
            saldo_consolidado = df_limpo[col_alvo].sum()
            
            dados_serie_temporal.append({
                "ano_mes": ano_mes,
                "saldo_empregos_rs": saldo_consolidado
            })
            print(f"✅ Processado: {ano_mes} | Coluna usada: '{col_alvo}' | Saldo: {saldo_consolidado:,.0f}".replace(",", "."))
        else:
            print(f"⚠️ Aviso: Coluna de saldo não identificada no arquivo {nome_fich}")
            
    except Exception as e:
        print(f"❌ Erro ao processar {nome_fich}: {e}")

# Transforma a lista de dicionários em um DataFrame estruturado
df_caged_cronologico = pd.DataFrame(dados_serie_temporal).sort_values("ano_mes").reset_index(drop=True)

print("\n📈 Série Temporal do CAGED RS para 2024 criada com sucesso!")
display(df_caged_cronologico)

🔄 Iniciando processamento de 127 arquivos em 2024...

❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_1.parquet: 'município'
⚠️ Aviso: Coluna de saldo não identificada no arquivo 10-tabelas-outubro-de-2024_tabela_10.parquet
⚠️ Aviso: Coluna de saldo não identificada no arquivo 10-tabelas-outubro-de-2024_tabela_11.parquet
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-10 | Coluna usada: 'outubro2024_sem_ajuste_saldos' | Saldo: 14.115
⚠️ Aviso: Coluna de saldo não identificada no arquivo 10-tabelas-outubro-de-2024_tabela_4.parquet
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 10-tabelas-outubro-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-10 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.672
✅ Processado: 2024-10 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 10-tabelas-outubro-de-2024_tabela_9.parquet
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_1.parquet: 'município'
⚠️ Aviso: Coluna de saldo não identificada no arquivo 12-tabelas-dezembro-de-2024_tabela_10.parquet
⚠️ Aviso: Coluna de saldo não identificada no arquivo 12-tabelas-dezembro-de-2024_tabela_11.parquet
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-12 | Coluna usada: 'dezembro2024_sem_ajuste_saldos' | Saldo: -28.384
⚠️ Aviso: Coluna de saldo não identificada no arquivo 12-tabelas-dezembro-de-2024_tabela_4.parquet
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 12-tabelas-dezembro-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-12 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.672
✅ Processado: 2024-12 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 12-tabelas-dezembro-de-2024_tabela_9.parquet
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_1.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-02 | Coluna usada: 'fevereiro2024_saldos' | Saldo: 25.452
⚠️ Aviso: Coluna de saldo não identificada no arquivo 2-tabelas-fevereiro-de-2024_tabela_4.parquet
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 2-tabelas-fevereiro-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-02 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.668
✅ Processado: 2024-02 | Coluna usada: 'janeiro2020_saldos' | Saldo: 11.562
⚠️ Aviso: Coluna de saldo não identificada no arquivo 2-tabelas-fevereiro-de-2024_tabela_9.parquet
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_1.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-03 | Coluna usada: 'março2024_saldos' | Saldo: 10.490
⚠️ Aviso: Coluna de saldo não identificada no arquivo 3-tabelas-marco-de-2024_tabela_4.parquet
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 3-tabelas-marco-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-03 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.665
✅ Processado: 2024-03 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 3-tabelas-marco-de-2024_tabela_9.parquet
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_1.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-04 | Coluna usada: 'abril2024_saldos' | Saldo: 13.512
⚠️ Aviso: Coluna de saldo não identificada no arquivo 4-tabelas-abril-de-2024_tabela_4.parquet
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 4-tabelas-abril-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-04 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.665
✅ Processado: 2024-04 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 4-tabelas-abril-de-2024_tabela_9.parquet
❌ Erro ao processar 5-tabelas-maio-2024_tabela_1.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-05 | Coluna usada: 'maio2024_saldos' | Saldo: -22.180
⚠️ Aviso: Coluna de saldo não identificada no arquivo 5-tabelas-maio-2024_tabela_4.parquet
❌ Erro ao processar 5-tabelas-maio-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 5-tabelas-maio-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-05 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.665
✅ Processado: 2024-05 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 5-tabelas-maio-2024_tabela_9.parquet
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_1.parquet: 'município'
⚠️ Aviso: Coluna de saldo não identificada no arquivo 7-tabelas-julho-de-2024_tabela_10.parquet
⚠️ Aviso: Coluna de saldo não identificada no arquivo 7-tabelas-julho-de-2024_tabela_11.parquet
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-07 | Coluna usada: 'julho2024_saldos' | Saldo: 6.690
⚠️ Aviso: Coluna de saldo não identificada no arquivo 7-tabelas-julho-de-2024_tabela_4.parquet
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 7-tabelas-julho-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-07 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.667
✅ Processado: 2024-07 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 7-tabelas-julho-de-2024_tabela_9.parquet
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_1.parquet: 'município'
⚠️ Aviso: Coluna de saldo não identificada no arquivo 8-tabelas-agosto-de-2024_tabela_10.parquet
⚠️ Aviso: Coluna de saldo não identificada no arquivo 8-tabelas-agosto-de-2024_tabela_11.parquet
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-08 | Coluna usada: 'agosto2024_saldos' | Saldo: 10.413
⚠️ Aviso: Coluna de saldo não identificada no arquivo 8-tabelas-agosto-de-2024_tabela_4.parquet
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 8-tabelas-agosto-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-08 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.668
✅ Processado: 2024-08 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 8-tabelas-agosto-de-2024_tabela_9.parquet
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_1.parquet: 'município'
⚠️ Aviso: Coluna de saldo não identificada no arquivo 9-tabelas-setembro-de-2024_tabela_10.parquet
⚠️ Aviso: Coluna de saldo não identificada no arquivo 9-tabelas-setembro-de-2024_tabela_11.parquet
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_2.parquet: 'município'
✅ Processado: 2024-09 | Coluna usada: 'setembro2024_saldos' | Saldo: 10.238
⚠️ Aviso: Coluna de saldo não identificada no arquivo 9-tabelas-setembro-de-2024_tabela_4.parquet
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_5.1.parquet: 'município'
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_5.parquet: 'município'
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_6.1.parquet: 'município'
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_6.parquet: 'município'
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_7.1.parquet: 'município'
❌ Erro ao processar 9-tabelas-setembro-de-2024_tabela_7.parquet: 'município'
✅ Processado: 2024-09 | Coluna usada: 'janeiro2020_saldos' | Saldo: 13.670
✅ Processado: 2024-09 | Coluna usada: 'janeiro2020_saldos' | Saldo: 12.075
⚠️ Aviso: Coluna de saldo não identificada no arquivo 9-tabelas-setembro-de-2024_tabela_9.parquet

📈 Série Temporal do CAGED RS para 2024 criada com sucesso!

    ano_mes  saldo_empregos_rs
0   2024-02            25452.0
1   2024-02            13668.0
2   2024-02            11562.0
3   2024-03            10490.0
4   2024-03            13665.0
5   2024-03            12075.0
6   2024-04            13512.0
7   2024-04            13665.0
8   2024-04            12075.0
9   2024-05           -22180.0
10  2024-05            13665.0
11  2024-05            12075.0
12  2024-07             6690.0
13  2024-07            13667.0
14  2024-07            12075.0
15  2024-08            10413.0
16  2024-08            13668.0
17  2024-08            12075.0
18  2024-09            10238.0
19  2024-09            13670.0
20  2024-09            12075.0
21  2024-10            14115.0
22  2024-10            13672.0
23  2024-10            12075.0
24  2024-12           -28384.0
25  2024-12            13672.0
26  2024-12            12075.0