In [12]:
# CÉLULA 1: Configuração do ambiente e definição de caminhos.
import pandas as pd
from pathlib import Path

#NOTE: Defina o arquivo e o ano processado.
ARQUIVO_ALVO = "12-tabelas-dezembro-de-2024_tabela_3.parquet"
ANO = "2024"

RAIZ = Path("..").resolve().parents[0]
CAMINHO_DADOS = RAIZ / "data" / "processed" / "caged-parquet" / ANO / ARQUIVO_ALVO

print(f"✅ Caminho configurado.")
print(f"🔍 Alvo: {CAMINHO_DADOS}")

✅ Caminho configurado.
🔍 Alvo: /home/lk1048/repositories/academic/estacio/ads-3-periodo/big-data/data/processed/caged-parquet/2024/12-tabelas-dezembro-de-2024_tabela_3.parquet

In [ ]:
# CÉLULA 2: Carregamento dos dados para a memória RAM.
if CAMINHO_DADOS.exists():
    df = pd.read_parquet(CAMINHO_DADOS)
    print(f"📊 Sucesso! O arquivo tem {df.shape[0]} linhas e {df.shape[1]} colunas.")
else:
    print(f"❌ Erro: Arquivo não encontrado em {CAMINHO_DADOS}")

❌ Erro: Arquivo não encontrado em /home/lk1048/repositories/academic/estacio/ads-3-periodo/big-data/data/processed/caged-parquet/2024/12-tabelas-dezembro-de-2024_tabela_3.parquet

In [14]:
# CÉLULA 3: Visualização inicial da estrutura dos dados.
df.head(10)

,UF,Código do Município,Município,Dezembro/2023 - sem ajuste Admissões,Dezembro/2023 - sem ajuste Desligamentos,Dezembro/2023 - sem ajuste Saldos,Dezembro/2023 - sem ajuste Variação Relativa (%),Acumulado do Ano (2023) Admissões,Acumulado do Ano (2023) Desligamentos,Acumulado do Ano (2023) Saldos,Acumulado do Ano (2023) Variação Relativa (%)
0,RO,110001.0,Ro-Alta Floresta D Oeste,56.0,97.0,-41.0,-2.0438683948155534,1188.0,1156.0,32.0,1.6376663254861823
1,RO,110002.0,Ro-Ariquemes,583.0,675.0,-92.0,-0.5067753663104549,11642.0,11035.0,607.0,3.443971631205674
2,RO,110003.0,Ro-Cabixi,10.0,6.0,4.0,0.9009009009009009,193.0,190.0,3.0,0.6651884700665188
3,RO,110004.0,Ro-Cacoal,753.0,774.0,-21.0,-0.12190166598943519,11617.0,11153.0,464.0,2.7647023774057082
4,RO,110005.0,Ro-Cerejeiras,90.0,94.0,-4.0,-0.17086715079026057,1455.0,1328.0,127.0,5.746606334841629
5,RO,110006.0,Ro-Colorado do Oeste,47.0,54.0,-7.0,-0.358974358974359,928.0,970.0,-42.0,-2.1549512570549
6,RO,110007.0,Ro-Corumbiara,46.0,62.0,-16.0,-1.1816838995568686,1038.0,828.0,210.0,18.71657754010695
7,RO,110008.0,Ro-Costa Marques,12.0,19.0,-7.0,-1.2681159420289856,264.0,268.0,-4.0,-0.7259528130671506
8,RO,110009.0,Ro-Espigao D Oeste,164.0,228.0,-64.0,-1.3608335105251965,2957.0,2924.0,33.0,0.7205240174672489
9,RO,110010.0,Ro-Guajara-Mirim,101.0,219.0,-118.0,-3.320202588632527,1888.0,1565.0,323.0,10.231232182451695

In [15]:
# CÉLULA 4: Listagem técnica das colunas.
print("🔍 Colunas encontradas (Normalizadas):")
for i, col in enumerate(df.columns):
    print(f"Coluna {i}: '{col}'")

🔍 Colunas encontradas (Normalizadas):
Coluna 0: 'UF'
Coluna 1: 'Código do Município'
Coluna 2: 'Município'
Coluna 3: 'Dezembro/2023 - sem ajuste Admissões'
Coluna 4: 'Dezembro/2023 - sem ajuste Desligamentos'
Coluna 5: 'Dezembro/2023 - sem ajuste Saldos'
Coluna 6: 'Dezembro/2023 - sem ajuste Variação Relativa (%)'
Coluna 7: 'Acumulado do Ano (2023) Admissões'
Coluna 8: 'Acumulado do Ano (2023) Desligamentos'
Coluna 9: 'Acumulado do Ano (2023) Saldos'
Coluna 10: 'Acumulado do Ano (2023) Variação Relativa (%)'

In [16]:
# CÉLULA 5: Extração e filtragem dos dados de interesse.

#NOTE: As colunas agora seguem o padrão 'nome_original_subtitulo' gerado na conversão.
coluna_desejada = 'seção_agrupamento' 

if coluna_desejada in df.columns:
    display(df[[coluna_desejada, df.columns[-1]]].head())
else:
    #NOTE: Caso a coluna exata mude entre tabelas, o display abaixo mostra o DF completo já limpo.
    display(df.head())

,UF,Código do Município,Município,Dezembro/2023 - sem ajuste Admissões,Dezembro/2023 - sem ajuste Desligamentos,Dezembro/2023 - sem ajuste Saldos,Dezembro/2023 - sem ajuste Variação Relativa (%),Acumulado do Ano (2023) Admissões,Acumulado do Ano (2023) Desligamentos,Acumulado do Ano (2023) Saldos,Acumulado do Ano (2023) Variação Relativa (%)
0,RO,110001.0,Ro-Alta Floresta D Oeste,56.0,97.0,-41.0,-2.0438683948155534,1188.0,1156.0,32.0,1.6376663254861823
1,RO,110002.0,Ro-Ariquemes,583.0,675.0,-92.0,-0.5067753663104549,11642.0,11035.0,607.0,3.443971631205674
2,RO,110003.0,Ro-Cabixi,10.0,6.0,4.0,0.9009009009009009,193.0,190.0,3.0,0.6651884700665188
3,RO,110004.0,Ro-Cacoal,753.0,774.0,-21.0,-0.12190166598943519,11617.0,11153.0,464.0,2.7647023774057082
4,RO,110005.0,Ro-Cerejeiras,90.0,94.0,-4.0,-0.17086715079026057,1455.0,1328.0,127.0,5.746606334841629